### ISSUE TITLE
Some KorGe artifacts aren't copied to JCenter

### ISSUE THREAD

**Issue by yvolk** [korlibs/korge-next#121]
I'm trying to publish my KorGe-based app to F-Droid Android Open Source apps repository (which builds apps itself), and it's hard to persuade F-Droid team to "Whitelist" 'https://dl.bintray.com/korlibs/korlibs' repo (see https://gitlab.com/fdroid/fdroidserver/-/issues/858 )

Jcenter repo *is* whitelisted in F-Droid and as I know, it's a matter of configuration / checkbox to start copying some artifacts from other bintray repos to Jcenter.

Meanwhile I see that some of KorGe artifacts are visible via Jcenter, but unfortunately not all. E.g. I see this in my build:
```
> Could not resolve all files for configuration ':debugRuntimeClasspath'.
   > Could not find com.soywiz.korlibs.korge:korge-android:2.0.3.
     Searched in the following locations:
       - file:/C:/Users/yuri/.m2/repository/com/soywiz/korlibs/korge/korge-android/2.0.3/korge-android-2.0.3.pom
       - https://dl.google.com/dl/android/maven2/com/soywiz/korlibs/korge/korge-android/2.0.3/korge-android-2.0.3.pom
       - https://jcenter.bintray.com/com/soywiz/korlibs/korge/korge-android/2.0.3/korge-android-2.0.3.pom
```

**Comment by soywiz** [comment]
I want to fix this ASAP. I will probably have to change the artifact name or the group. Probably from korge to korge2.

**Comment by soywiz** [comment]
I have deployed `2.0.5` here: https://bintray.com/korlibs/korlibs/korge2
And already sent a request to include that korge2 group/package in jcenter. Let's keep this open until they reply.

**Comment by soywiz** [comment]
Included already on jcenter!
