### ISSUE TITLE
2.0.7.0 breaks clicks on mobile device browser in my game

### ISSUE THREAD

**Issue by SerVB** [korlibs/korge-next#193]
Found out that for some time clicks don't work when I open my game in a mobile web browser.

I see errors in console, seems like e.touches is empty (on this line: https://github.com/korlibs/korge-next/blob/498c12a1cd80272b8673ea2e736ad72410369389/korge/src/commonMain/kotlin/com/soywiz/korge/Korge.kt#L373)

![image](https://user-images.githubusercontent.com/20105593/110218243-9ea3e700-7ec9-11eb-9a96-e2c8fd9f0f7c.png)

I've investigated a bit: checked git history and saw this PR: https://github.com/korlibs/korge-next/pull/162

It seems that it spoils touches: on 2.0.7.0 (with this PR merged), the bug persists; on 2.0.6.0 (before this PR), clicks work fine.

To reproduce, you can build my game. Here it has KorGE 2.0.7.0: https://github.com/SerVB/pph/blob/e478eff981571ec5bd4370010ceb03f947b6ea5b/gradle.properties#L1. If you access the built game via Mobile Chrome, clicks will produce exceptions. If you change the version to 2.0.6.0, clicks will work fine.

**Comment by soywiz** [comment]
Fuck my life :) lol

That change was pretty critical. I'll try to fix this in the next version. Fortunately now I can compile to iOS and Mac again, so I'll check on all the targets, variants retina/non-retina and hopefully get it working properly now.

**Comment by SerVB** [comment]
This issue is critical for me because I can't update to newer KorGE versions. I've debugged a bit. I see that before that PR, the list of touches was not cleared on touch end, but now it is cleared always when a new touch received (`_touches.clear()`):

https://github.com/korlibs/korge-next/blob/0a4c743a31bdd4a17ee000d689b55f5e5f859aa4/korgw/src/commonMain/kotlin/com/soywiz/korev/Events.kt#L104-L115

https://github.com/korlibs/korge-next/blob/8eb9dcd1bf8a9fd1bc2b930d16e401da17d9a3f0/korgw/src/commonMain/kotlin/com/soywiz/korev/Events.kt#L105-L109

The problem here is that in JS, the native list of touches contains only touches that are contacting with the surface when the event happens ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent/touches)), so on touch end, `e.touches.end` is 0 and no touches are added to `touchEvent` after `startFrame` that clears touches:

https://github.com/korlibs/korge-next/blob/15d618b6d771b87ef788f4a859c9f548e7c0f0e7/korgw/src/jsMain/kotlin/com/soywiz/korgw/DefaultGameWindowJs.kt#L196-L208

I've tried to add condition to `startFrame`, but it seems it introduces other touch bugs, and doesn't completely fix the missing touch on touch end:

```kotlin
if (type != Type.END) {
    _touches.clear()
}
```

Anyway, judging by [Android Docs](https://developer.android.com/reference/android/view/MotionEvent), it seems touches list is non-empty there on touch end, so the current logic of clearing touches should work well for Android.

I will try to research further but I'm not sure I will be lucky to refactor KorGE JS touch handler properly... @soywiz, maybe you could handle this faster.
