### ISSUE TITLE
applicationDataVfs.VfsFile.delete() does nothing when running in browser

### ISSUE THREAD

**Issue by jfbilodeau** [korlibs/korge-next#233]
Attempting to delete a file in LocalStorage using VfsFile in JS doesn't seem to do anything.

**Comment by soywiz** [comment]
This was fixed here: https://github.com/korlibs/korge-next/issues/201 I cannot reproduce it with korge-next

I'm not sure if this is in the latest version of KorGE, but the fix if not already published will be available on the next version published.


You can try it by cloning next, then adding this lines to `samples/hello-world/src/commonMain/kotlin/main.kt`

```kotlin
applicationDataVfs["hello.txt"].writeString("hello world!")
println(applicationDataVfs["hello.txt"].takeIfExists()?.readString())
applicationDataVfs["hello.txt"].delete()
println(applicationDataVfs["hello.txt"].takeIfExists()?.readString())
```

Then execute:
```
gradlew :samples:hello-world:runJs
```

**Comment by jfbilodeau** [comment]
Thanks Soywiz. I'll test later next week!
