### ISSUE TITLE
[Support plugins block] Could not resolve plugin artifact 'com.soywiz.korge:com.soywiz.korge.gradle.plugin:VERSION'

### ISSUE THREAD

**Issue by SerVB** [korlibs/korge-next#257]
I see that all the KorGE examples use the legacy way of applying the gradle plugin:

https://github.com/korlibs/korge-hello-world/blob/d223fa3c62163cc13375d7d522c0740ecb52d818/build.gradle.kts#L3-L17

I want to use the plugins block like this:

```kt
pluginManagement {
    repositories {
        mavenLocal()
        maven("https://dl.bintray.com/korlibs/korlibs")
        maven("https://plugins.gradle.org/m2/")
        mavenCentral()
        google()
        maven("https://dl.bintray.com/kotlin/kotlin-dev")
        maven("https://dl.bintray.com/kotlin/kotlin-eap")
    }

    val korgePluginVersion: String by settings

    plugins {
        id("com.soywiz.korge") version korgePluginVersion
    }
}
```

However, it seems that the artifact name is not canonical now so Gradle can't find it (it worked a couple of versions ago in KorGE 2.0 but it doesn't work for KorGE 2.1). To make it work now, I need to specify the following:

```kt
pluginManagement {
    repositories {
        mavenLocal()
        maven("https://dl.bintray.com/korlibs/korlibs")
        maven("https://plugins.gradle.org/m2/")
        mavenCentral()
        google()
        maven("https://dl.bintray.com/kotlin/kotlin-dev")
        maven("https://dl.bintray.com/kotlin/kotlin-eap")
    }

    val korgePluginVersion: String by settings

    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "com.soywiz.korge") {
                useModule("com.soywiz.korlibs.korge.plugins:korge-gradle-plugin:$korgePluginVersion")
            }
        }
    }

    plugins {
        id("com.soywiz.korge")
    }
}
```

Could you use canonical artifact ID (`com.soywiz.korge:com.soywiz.korge.gradle.plugin`) for publishing the plugin? Maybe it's worth switching all the examples to the new way of applying the plugin afterwards.

**Comment by soywiz** [comment]
Any tips on how should I configure it?

Relevant fragment: https://github.com/korlibs/korge-next/blob/c50d3f96d184d9d7837b3cf4121938dfd6c566a9/korge-gradle-plugin/build.gradle.kts#L11-L29

**Comment by soywiz** [comment]
This is what it seems that is being published:

![Uploading 2021-07-25_9-25-02.png…]()

**Comment by soywiz** [comment]
These seems the packages that are being published (please, ignore versions):

![2021-07-25_9-25-02](https://user-images.githubusercontent.com/570848/126891279-d88c1fd9-ce43-40d2-becb-de1a0048f4b0.png)

**Comment by SerVB** [comment]
> Any tips on how should I configure it?

Idk... And I don't have enough time to research it (probably some info about creating Gradle Plugins) in the near future. Probably you've seen that in [korjector](https://github.com/SerVB/korjector/blob/3b7c606531fdce158f7243a1680b0fe3e61b5eb4/settings.gradle.kts#L10-L16) I still used `resolutionStrategy` to make it work.

Maybe somebody else could research that. Or I hope I'll do it someday...

**Comment by soywiz** [comment]
Okay. No problem, thanks for letting me know. I’m not going to investigate this in the short term either.
I believe this would be a Quick Win if someone knows how to do it, but if not the investigation might be a bit too much work for the benefit.

**Comment by soywiz** [comment]
Fixed https://github.com/korlibs/korge-hello-world/pull/19/files
