### ISSUE TITLE
TileMap ignoring Offset

### ISSUE THREAD

**Issue by Selemba1000** [korlibs/korge-next#327]
When trying to exxtract the collision-data from a tileset, i noticed that the objectShape has no x and y coordinates.
[Offset Test.zip](https://github.com/korlibs/korge-next/files/6895901/Offset.Test.zip) This tileset includes all intresting cases.
1. Tile 0 has a square hitbox starting at 0,0 with size 16. It is correctly parsed to bounds and objectShape.
2. Tile 1 has a square hitbox starting at 8,8 with size 8. It is correctly parsed to bounds, but as objectShape contains no x and y coordinates, objectShape.toVectorpath puts the hitbox at 0,0
3. Tile 2 has a polygon hitbox that does not start on 0,0. It is not correctly read at all. bounds contain correct x and y to the start point, but as width and heigth are not set on polygons, it is quite useless. objectShape then only contains all the points, but not the corrrect startpoint.

For now i can work arround case 2, by using the bounds as input, and not objectShape.toVectorPath. For case 3 i tried to use a translate-matrix on the points of objectShape, fitted with the x and y of bounds, but for now it doesn't work for me. I probably messed something up with the matrix.

**Annoyment level**
 It is inconvenient, but I can circumvent the issue for now

I really appreciate your work here. Thanks for looking at this.
Sorry i'm no good at memes. :)

**Comment by soywiz** [comment]
I was not able to reproduce it in tests. The offset seems to be taken into account. Can you indicate me how to reproduce the issue with code?

**Comment by Selemba1000** [comment]
Ok that was my error. So toVectorpath() applys the needed transform. I tried to use objectShape directly, wich does not have the transform. I can adapt my code to that now. Thanks for the help anyways.
