### ISSUE TITLE
Extrude tiles while reading tiled map into atlas

### ISSUE THREAD

**Issue by jobe-m** [korlibs/korge-next#332]
- Possibility to extrude the tiles within a tileset (This is useful to prevent seams when scrolling the tiled view.)
This is related to #314

With this issue I want to check why by calling `resourcesVfs["file.tmx"].readTiledMap(atlas = atlas)` the tiles does not get into the provided atlas object.

**Comment by jobe-m** [comment]
While reading through the sources I saw that the atlas parameter is never taken.

https://github.com/korlibs/korge-next/blob/b198559574de924056213669ec29bfc90e8a40e7/korge/src/commonMain/kotlin/com/soywiz/korge/tiled/TiledMapReader.kt#L67

When changing that line into:
```
    //val atlas = if (atlas == null || createBorder > 0) MutableAtlasUnit(2048, border = createBorder.clamp(2, 4)) else null
    val atlas = atlas ?: MutableAtlasUnit(2048, border = (createBorder * 2).clamp(0, 4))
```
then the given atlas is taken and the tiles appear in the external atlas object. I also thing that extruding the tiles makes always sence but might also be specified by the createBorder parameter.
Does these changes make sence? I will also check a bit further...

**Comment by soywiz** [comment]
I see. That makes sense. But I believe there is a third case: When you don't provide atlas, and also don't request an extrude/border. In which case the expression should be null, and the original texture should be used

So maybe something like:

```
when {
  atlas != null -> atlas
  createBorder > 0 -> MutableAtlas(…)
  else -> null
}
```

**Comment by jobe-m** [comment]
Yes, right. Looks good. I will take that over.
