### ISSUE TITLE
Cannot load tiledmaps where Tilesets are not in the same folder as the Tiledmap (relative path issue)

### ISSUE THREAD

**Issue by v79** [korlibs/korge-next#399]
**Describe the bug**

Using Korge next (2.4.8 / 2.0.0.999 and Kotlin 1.6), Korge cannot load a .tmx TiledMap if it references .tsx TileSets stored in a different directory than the .tmx. For example, given this .tmx XML:

```xml
 <tileset firstgid="1" source="32x32_map_tile.tsx"/>
 <tileset firstgid="668" source="../dungeon/Dungeon.tsx"/>
```
The first .tsx file loads correctly, but the second fails with the following error:

`java.io.FileNotFoundException: D:\Development\Games\Korge\TheAlchemist\src\commonMain\resources\maps\village\dungeon\Dungeon.tsx (The system cannot find the path specified)`

The correct path should be:  `D:\Development\Games\Korge\TheAlchemist\src\commonMain\resources\maps\dungeon\Dungeon.tsx`
I'm guessing the trouble is somewhere in korio/file but I haven't been able to track it down.

**Annoyment level**

> How annoyed are you in a scale of 1-3 because this shitty code doesn't work properly

* [x] 1 - No rush from my side
* [ ] 2 - It is inconvenient, but I can circumvent the issue for now
* [ ] 3 - FUUUU
* [ ] 4

**Payment**

> How do you plan to compensate the time we will invest fixing this?

* [x] I will add a message with "Thanks" when merged to let you know I'm grateful
* [ ] I will also add a [meme image](https://imgflip.com/memegenerator) relevant to the issue to make you smile so we both have fun
* [ ] In fact, I'm going to add a meme here in this issue too
* [ ] I'm going to write about KorGE in my blog, spread the voice on social networks, or maybe even make a TikTok wearing a KorGE T-Shirt while dancing

> You can also consider donating some money via Github Sponsors to the person fixing the issue.

**Meme**

> Here you can put a meme to motivate us to fix the issue.

**Comment by jobe-m** [comment]
I had seen once the same problem. Actually you need to have the tileset (tsx) file in the same directory as the tilemap (tmx) file or in a subdirectory. That is actually limiting larger projects which would reuse tilesets in multiple levels (tmx files).
So Korge should allow tilesets (tsx) to sit outside of the folder which contains the tilemaps (tmx).

When I have time this evening I can look into it.

**Comment by v79** [comment]
Thanks!
