### ISSUE TITLE
klock lacks support for ios_simulator_arm64 (M1)

### ISSUE THREAD

**Issue by metcheverr-chwy** [korlibs/korge-next#404]
**Describe the bug**

We are trying to build a kotlin native library that uses klock, we want to have a target for `ios_simulator_arm64` to get such a wonderful slice in our xcframework. None of the other libraries we use seem to have an issue (updating them to the latest version gives us M1 support).

I believe `klock` has not been updated to support `ios_simulator_arm64`, at least not in the latest public release 2.4.8:

See: https://repo1.maven.org/maven2/com/soywiz/korlibs/klock/klock/2.4.8/klock-2.4.8-kotlin-tooling-metadata.json

It does seem like the top level gradle file for `korge-next` does support `ios_simulator_arm64`.

CC: @soywiz 

Here is the error message:

> No matching variant of com.soywiz.korlibs.klock:klock:2.4.8 was found. The consumer was configured to find a usage of 'kotlin-api' of a library, preferably optimized for non-jvm, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native', attribute 'org.jetbrains.kotlin.native.target' with value 'ios_simulator_arm64' but:

<hr>
Happens on macOS 11.6.1. Gradle 7.0. Android Studio 2020.3

PATH is `export PATH="/Applications/Android Studio.app/Contents/jre/Contents/Home/bin:$PATH"`

`Dependency.kt` is as follows:
```
object Versions {
    const val MIN_SDK = 23
    const val COMPILE_SDK = 30
    const val TARGET_SDK = 30

    const val kotlin = "1.6.10"

    const val androidTools = "4.1.1"

    const val coroutines = "1.5.2-native-mt"

    const val serialization = "1.3.0"

    const val ktor = "1.6.5"

    const val klock = "2.4.8"

    const val benasherUUID = "0.3.1"

    const val stately = "1.2.0"

    const val junit = "4.12"

    const val sqlDelight = "1.5.3"
}
```

**Annoyment level**

> How annoyed are you in a scale of 1-3 because this shitty code doesn't work properly

* [x] 1 - No rush from my side
* [ ] 2 - It is inconvenient, but I can circumvent the issue for now
* [ ] 3 - FUUUU

**Payment**

> How do you plan to compensate the time we will invest fixing this?

* [x] I will add a message with "Thanks" when merged to let you know I'm grateful
* [x] I will also add a [meme image](https://imgflip.com/memegenerator) relevant to the issue to make you smile so we both have fun
* [x] In fact, I'm going to add a meme here in this issue too
* [ ] I'm going to write about KorGE in my blog, spread the voice on social networks, or maybe even make a TikTok wearing a KorGE T-Shirt while dancing

**Meme**

![image](https://user-images.githubusercontent.com/90644563/146280601-7cb6ddfe-8a20-43bc-b01e-3244d544821c.png)

**Comment by soywiz** [comment]
I believe this was fixed here last week: https://github.com/korlibs/korge-next/commit/6cd95f2b2aff707a23821f648200f1d20304e30e

We cannot trigger a release because windows has to be fixed first because something changed in the native toolchain

**Comment by soywiz** [comment]
Supported in https://github.com/korlibs/korge-next/releases/tag/v2.4.9
