### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by Jon889** [korlibs/korge-next#406]
It looks like Apple Silicon support was added in 2.4.9 (The arm64 simulators) but when trying to use Klock, I get this error:

```
Could not find com.soywiz.korlibs.klock:klock-iossimulatorarm64:2.4.9.
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/com/soywiz/korlibs/klock/klock-iossimulatorarm64/2.4.9/klock-iossimulatorarm64-2.4.9.pom
  - https://jcenter.bintray.com/com/soywiz/korlibs/klock/klock-iossimulatorarm64/2.4.9/klock-iossimulatorarm64-2.4.9.pom
  - https://jitpack.io/com/soywiz/korlibs/klock/klock-iossimulatorarm64/2.4.9/klock-iossimulatorarm64-2.4.9.pom
  - https://s01.oss.sonatype.org/content/repositories/snapshots/com/soywiz/korlibs/klock/klock-iossimulatorarm64/2.4.9/klock-iossimulatorarm64-2.4.9.pom
Required by:
    project :shared > project :lib:core > com.soywiz.korlibs.klock:klock:2.4.9
```

Is support fully added yet?

**Comment by soywiz** [comment]
Woops. It seems that I forgot to add it to the deployment CI:
https://github.com/korlibs/korge-next/commit/b7611004ce35960d9876eca2cc4c1fd0ccab247c

Triggered a new build:
https://github.com/korlibs/korge-next/releases/tag/v2.4.10

Also, please note that the repos you put in the snippet seems outdated. Jcenter doesn't exist anymore, snapshots shouldn't contain this version, and jitpack+klock is not going to contain the artifacts.
You should use `mavenCentral()` instead.

If CI works properly, the new artifact should be here: https://repo.maven.apache.org/maven2/com/soywiz/korlibs/klock/klock-iossimulatorarm64/

**Comment by Jon889** [comment]
Thanks so much :)

Yeah I saw the warnings and I had tried using mavenCentral but something else then went wrong. I’m quite new to Android/Kotlin multi platform, so still learning! Thanks for the info :)
