### ISSUE TITLE
SVG renderer issue

### ISSUE THREAD

**Issue by Kietyo** [korlibs/korge-next#435]
**Describe the bug**

```
suspend fun main() = Korge(width = 640, height = 360, bgcolor = Colors.LIGHTGRAY) {
	val tonPng = resourcesVfs["tiles/Regular/Man1.svg"].readSVG().render()
	image(tonPng) {
		scale = 0.5
	}
}
```

Expected:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/5054996/152093709-36243368-757f-49c7-823e-e3395e536043.png">

Actual:
<img width="485" alt="image" src="https://user-images.githubusercontent.com/5054996/152093739-d5ac0f8d-9293-44ff-9b37-84f65d7d10d5.png">

File:
![Man1](https://user-images.githubusercontent.com/5054996/152093793-736ef674-ca0f-4c7d-be69-eb9a90dc8ca2.svg)

More examples of svg files with messed up rendering can be found here:

https://github.com/FluffyStuff/riichi-mahjong-tiles

**Comment by soywiz** [comment]
This seems to be the offending path:

```xml
        <path
           sodipodi:nodetypes="cccccc"
           inkscape:connector-curvature="0"
           id="path6023"
           d="m -881.54242,246.32019 -19.23296,0.63476 -5.29091,90.55948 c -0.75114,10.29193 4.49195,20.6109 11.24113,20.7628 l 18.7421,-6.5465 z"
           style="fill:#b93c3c;fill-opacity:1;fill-rule:evenodd;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1" />
```
