### ISSUE TITLE
Text clipping from bottom

### ISSUE THREAD

**Issue by sahilbajaj** [korlibs/korge-next#437]
**Describe the bug**

> Some fonts get clipped from bottom. Choosing an external ttf font ('Pacifico.ttf') in  :samples:text sample reproduces the issue.
As is noticeable from the attached screenshot, the letter g gets clipped.

**Annoyment level**

> How annoyed are you in a scale of 1-3 because this shitty code doesn't work properly

* [ ] 1 - No rush from my side
* [ ] 2 - It is inconvenient, but I can circumvent the issue for now
* [x] 3 - FUUUU
* [ ] 4

**Payment**

> How do you plan to compensate the time we will invest fixing this?

* [x] I will add a message with "Thanks" when merged to let you know I'm grateful
* [ ] I will also add a [meme image](https://imgflip.com/memegenerator) relevant to the issue to make you smile so we both have fun
* [ ] In fact, I'm going to add a meme here in this issue too
* [x] I'm going to write about KorGE in my blog, spread the voice on social networks, or maybe even make a TikTok wearing a KorGE T-Shirt while dancing
<img width="964" alt="Screenshot 2022-02-10 at 1 09 56 PM" src="https://user-images.githubusercontent.com/4324550/153360057-2554a7f1-9428-4b0a-885e-e5a067ab0bcb.png">

**Comment by sahilbajaj** [comment]
It gets more interesting..
It happens only If I add a text inside a container.

```
        val font = resourcesVfs["Pacifico.ttf"].readTtfFont()
        val container = Container()
        val text = Text("WTF is going on", 44.0, Colors.BLUEVIOLET, font)

        container.addChild(text)
```

**Comment by soywiz-invideo** [comment]
@sahilbajaj :

<img width="1212" alt="Screenshot 2022-02-16 at 15 26 46" src="https://user-images.githubusercontent.com/99644907/154285075-7a3a079d-06c8-4665-a106-4306bc3161fb.png">

Maybe another circumstance is also required? Was that code tried with the latest version of KorGE?

**Comment by sahilbajaj** [comment]
Why is it all happening with me! :(
let me check and get back to you

**Comment by sahilbajaj** [comment]
<img width="524" alt="Screenshot 2022-02-16 at 9 57 34 PM" src="https://user-images.githubusercontent.com/4324550/154310779-b11183d3-cba7-45ea-9a4b-143dd1e29210.png">

Why does it look different for me?

**Comment by WarrenFaith** [comment]
For me it does not matter if there is a container around the text or not (running with latest 2.5.0)

![Screenshot 2022-02-17 at 18 08 07](https://user-images.githubusercontent.com/152264/154533769-994f6a81-2349-45d8-927f-8ffde86aedec.png)

```
suspend fun main() {
	Korge(
		debug = true,
		width = 960,
		height = 720,
		bgcolor = DEFAULT_BG,
		clipBorders = false,
		scaleAnchor = Anchor.TOP_LEFT
	) {
		val font = resourcesVfs["Pacifico.ttf"].readTtfFont()
		val container = Container()
		val text = Text("WTF is going on", 44.0, Colors.BLUEVIOLET, font)
		text.pos = Point(0, 100)
		container.debugAnnotate = true
		container.addChild(text)
		addChild(container)

		val text2 = Text("WTF is going on", 44.0, Colors.BLUE, font)
		text2.pos = Point(0, 200)
		text2.debugAnnotate = true
		addChild(text2)
	}
}
```

**Comment by soywiz** [comment]
Yeah, the problem was with the ttf file. I had another one with the same name that didn't reproduce the isssue

**Comment by soywiz** [comment]
Fixed here: https://github.com/korlibs/korge-next/commit/ce9fd5ea8b995dd535bc50db9397d0d95faa7861
