### ISSUE TITLE
Trilinear filtering

### ISSUE THREAD

**Issue by BioRyajenka** [korlibs/korge-next#461]
Hello, thank you for awesome engine. 

I saw korge has mipmaps. Does it have trilinear texture filtering as well?

**Comment by soywiz** [comment]
@BioRyajenka What's your use-case here? Isn't trilinear filter useful for projection transforms and 3D?

**Comment by BioRyajenka** [comment]
Well I know some people use it for smooth zooming in their games, and wanted to do same. 
Here factorio guys mention it in their blog (search for "trilinear")

**Comment by BioRyajenka** [comment]
So, the idea is that using trilinear filtering you can guarantee not blurred picture even for high zoom values

**Comment by soywiz** [comment]
I see, thanks for the clarification! I believed I was confused trilinear with the anisotropic filter: https://en.wikipedia.org/wiki/Anisotropic_filtering

So I guess trilinear is like sampling two mipmap levels together.
KorGE is not doing that right now, but can be implemented 👍
