### ISSUE TITLE
Having build issue

### ISSUE THREAD

**Issue by honorthrawn** [korlibs/korge-next#572]
When trying to build and run for android, I get the following error:

> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'androidsupportmultidexversion.txt' from inputs:
      - C:\Users\honor\.gradle\caches\transforms-3\eec09900e84aadeceee52e2dd6e3acd5\transformed\multidex-2.0.0\jars\classes.jar
      - C:\Users\honor\.gradle\caches\transforms-3\c7bef13cc62e7a056a140300e38b4b82\transformed\multidex-1.0.3\jars\classes.jar
     Adding a packagingOptions block may help, please refer to
     https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html
     for more information
This occurs with the project template/hellow world example project.

**Comment by rjframe** [comment]
As a workaround you can add the following to `build/platforms/android/build.extra.gradle`:

```gradle
android {
    packagingOptions {
        exclude '**/androidsupportmultidexversion.txt'
    }
}
```
