### ISSUE TITLE
support for SHA512

### ISSUE THREAD

**Issue by benkuly** [korlibs/korge-next#617]
It would be really cool to have support for SHA512 in krypto.
I also think `HMAC.hmac(...)` and `PBKDF2.pbkdf2(...)` should be public to let the user decide, which Hasher they want to use.

I'm willing to sponsor this :)

**Comment by soywiz** [comment]
Can I ask what's your use-case for SHA512?

**Comment by benkuly** [comment]
For `Pbkdf2Sha512`, which is defined by [Matrix Client-Server Spec](https://spec.matrix.org/v1.2/client-server-api/#key-exports).

**Comment by benkuly** [comment]
Awesome! That was fast. Thank you very much!
