### ISSUE TITLE
support AES-CTR

### ISSUE THREAD

**Issue by benkuly** [korlibs/korge-next#619]

**Comment by soywiz** [comment]
@benkuly  What's your use-case for AES-CTR?

**Comment by benkuly** [comment]
I'm the maintainer of [Trixnity](https://gitlab.com/benkuly/trixnity), a Kotlin multiplatform Matrix SDK. Matrix does encrypt messages via AES-CTR: https://spec.matrix.org/v1.2/client-server-api/#sending-encrypted-attachments

**Comment by soywiz** [comment]
@benkuly Nice. So you want: https://gitlab.com/benkuly/trixnity/-/blob/047501a0e0bd0d21936c6d66095985dfcdaeadd5/trixnity-client/src/commonMain/kotlin/net/folivo/trixnity/client/crypto/aes.kt#L3 this to become something common kotlin? How are you implementing it in native right now?

**Comment by benkuly** [comment]
Exactly.
I does not support native right now (only JVM, JS/NodeJS). I saw that korge seems to have a kotlin implementation of AES and it may be possible to support CTR. If not, then I will try to use libcrypto :)

**Comment by benkuly** [comment]
Wow! I'm so impressed how fast you did that. Thank you :)

**Comment by soywiz** [comment]
@benkuly Np! Checked and looked reasonably simple, and also took the opportunity to generalize a few things and simplify the code that the mode was couples to the AES implementation
