### ISSUE TITLE
Migration layer: inline fun + deprecated with error

### ISSUE THREAD

**Issue by soywiz** [korlibs/korge-next#63]

**Comment by soywiz** [comment]
https://github.com/korlibs/korge-next/pull/78

@avdim can I close this issue, or there is something missing?

**Comment by avdim** [comment]
@soywiz I think that I can improve further, but I don't know when I can find the time for this

**Comment by soywiz** [comment]
Okay, then let's keep this open. I plan to prepare the 2.0.0 release tomorrow, but we can make a 2.0.1 release with additions that do not change the published API, like adding these transition methods.
