### ISSUE TITLE
readBitmap on NodeJs throws UnsupportedOperationException

### ISSUE THREAD

**Issue by benkuly** [korlibs/korge-next#630]
I get `UnsupportedOperationException: No suitable image format : MAGIC:ﾉPNG(89504e47) (ﾉPNG)`
when running this code in nodeJs. It works on JVM and js/browser:

```kotlin
suspend fun createThumbnail(file: ByteArray, maxWidth: Int, maxHeight: Int): Thumbnail {
    val image = file.asMemoryVfsFile().readBitmap() <-- The exception throws here.
    val resizedImage = image.resizedUpTo(maxWidth, maxHeight)
    return Thumbnail(resizedImage.encode(PNG), ContentType.Image.PNG, resizedImage.width, resizedImage.height)
}
```

Any idea? Maybe I'm using the API incorrectly.

**Comment by soywiz** [comment]
In the browser it uses the API from the browser to decode images. In the cae of Node, you have to manually register formats as a fallback mechanism.

https://github.com/korlibs/korge-next/blob/d0514d0d9447e93661f8018180643203a03f1d2a/korim/src/commonMain/kotlin/com/soywiz/korim/format/RegisteredImageFormats.kt#L16

```kotlin
RegisteredImageFormats.register(PNG)
```

In the case you also need JPEG, feel free to use this code:
https://github.com/korlibs/korge-next/tree/d0514d0d9447e93661f8018180643203a03f1d2a/%40old/korim-jpeg/src/commonMain/kotlin/com/soywiz/korim/format/jpg

It is not included to simplify the license in korim, but the original code is Apache 2.0

**Comment by benkuly** [comment]
Thank you! Is there a way to just register all supported formats as fallback, if native decoding does not work?

**Comment by soywiz** [comment]
Nope. They are not automatically registered to allow DCE to work properly. And no method referencing all the image formats either. Maybe you don't wait QOI or PSD.
But you can check the package with the formats and see the ones available that you are interested in, and add them. Since it is a vararg, you can: `.register(PNG, JPEG, BMP, TGA, PSD)` etc.
