### ISSUE TITLE
Video about 2.0

### ISSUE THREAD

**Issue by soywiz** [korlibs/korge-next#66]

**Comment by emign** [comment]
Any news on the Reset button?

**Comment by soywiz** [comment]
I added it already the other day on korge-next.

Unfortunately as told you all the code for the intellij plugin referencing the other projects was red without autocompletion due probably to a regression even when it was compiling, so cannot investigate right now the issues you told me.

Do you really need that for doing this issue or can somehow not use it or use it in a way where the issues are not appearing?

**Comment by emign** [comment]
I think an essential part is missing then but ofc I can produce the video without a reset button. I'll do that

**Comment by soywiz** [comment]
As we talked already Nico, I'm reducing the scope of this to just the video. I will handle the blogpost 👍

**Comment by soywiz** [comment]
Thanks Nico!

**Comment by soywiz** [comment]
![](https://media2.giphy.com/media/3ndAvMC5LFPNMCzq7m/giphy-downsized-medium.gif)
