### ISSUE TITLE
Provide all operations of Bezier.JS

### ISSUE THREAD

**Issue by soywiz** [korlibs/korge-next#694]
* https://pomax.github.io/bezierjs/
* https://pomax.github.io/bezierinfo/

We will also need a way to get `t` from a specific `length` so we can compute points at a regular distance. Guess we can do that with a LUT table.

To simplify bezier cubic bezier curves into quadratic, to do curve rendering on the GPU easily, intersection points.
Also the outline can be used to generate strokes

**Comment by soywiz-invideo** [comment]
Implemented everything but curvature, offset, arcs and outline variants

**Comment by soywiz-invideo** [comment]
Done. Modulo outline shapes and arcs approximation.
