### ISSUE TITLE
RoundRect color is white

### ISSUE THREAD

**Issue by faweizz** [korlibs/korge-next#702]
In 3.0.0-Beta3 roundrects with the property color are getting rendered white. 
Using fill works. Is removing color planned?

When i set stroke and strokethickness there is no border drawn.

Tested on JVM and JS

**Comment by soywiz** [comment]
Woops. No: RoundRect, Circle and other views extending ShapeView are now using a new GpuVectorView implementation that is completely new and renders without intermediate textures. I was not aware of this issue so thanks for noticing. Can you create an issue reporting this?

**Comment by soywiz** [comment]
Woops. I readed this in my phone and I believed it was a comment in the Beta3 release, not that it was an actual issue :)
So let's close this and use the other one as reference: https://github.com/korlibs/korge-next/issues/703
