### ISSUE TITLE
Applying filters on views results in significant performance degradation

### ISSUE THREAD

**Issue by cbreezier** [korlibs/korge-next#704]
Applying even a single filter results in a noticeable FPS hiccup. Applying multiple filters results in a significant FPS drop from ~120FPS to ~20FPS on my machine.

Minimal reproduction: https://github.com/cbreezier/korge-bug-repros/tree/594bcec7f7483ad7128ee7096e5ffd42313c42ef

Relevant snippet:
```
	launch {
		while (true) {
			delay(2.seconds) // just to show that normal FPS is good, but every 2 seconds we get a big drop
                         // 30 images here - standard image views
			for (image in images) {
				image.filter = if (Random.nextBoolean()) {
					ColorMatrixFilter(ColorMatrixFilter.SEPIA_MATRIX)
				} else {
					ColorMatrixFilter(ColorMatrixFilter.GRAYSCALE_MATRIX)
				}
			}
		}
	}
```

**Comment by cbreezier** [comment]
[filter-low-fps.nps.zip](https://github.com/korlibs/korge-next/files/8798079/filter-low-fps.nps.zip)

Not sure I've done this correctly, but I've attached a snapshot of a CPU sample from VisualVM.

If I'm interpreting it correctly, it seems like the bottleneck is in `compileShader`:
![image](https://user-images.githubusercontent.com/4517105/170987298-c2c182ef-11f0-402e-bd70-5e1dd5999ffe.png)

Is it normal to be "compiling" the shader live like this? Am I doing something wrong, and should somehow precompile the shaders needed for using a `ColorMatrixFilter`? Or could it have something to do with the M1 Mac?

**Comment by cbreezier** [comment]
Ah, I've found my issue. By constructing a new `ColorMatrixFilter` every time, it counts as a separate `GlProgram` (see AGOpengl) because the cache of `GlProgram`s uses an identity map. This means that each new filter requires a new shader to be compiled, which is what tanks the performance.

If I construct one `ColorMatrixFilter` at the start, and reuse it throughout the program, I don't see my ongoing FPS issue. It's still a bit slow to start up and the FPS is a bit jittery at the start, but I assume I can get around this by having some kind of loading screen while I pre-warm my filters.

Is this the expected behaviour? I was hoping that it would be possible to dynamically create arbitrary filters without the performance penalty.

If this is the expected behaviour, I'll probably open a PR to update the docs to mention this, because there isn't any warning there at the moment: https://docs.korge.org/korge/reference/filters/

**Comment by soywiz** [comment]
Thanks for the detailed report @cbreezier it helped a lot to quickly figure out the problem!
