### ISSUE TITLE
androidMain folder is not included in the android sourceSet

### ISSUE THREAD

**Issue by soywiz** [korlibs/korge-next#71]

**Comment by yvolk** [comment]
Android support in current korge-gradle-plugin is too limited to allow creation of anything beyond sample application. But this limitation actually can be worked around by manual copying of the plugin-generated Android project to a separate location and its customization. Including manual addition of "androidMain" folder to the Android project's sourceSet.
See e.g. https://github.com/andstatus/game2048/tree/master/game2048-android

What's really inconvenient in such an approach, is that  the "androidMain" folder is not recognized as a SourceSet in the root project, where we are supposed to develop most of the multiplatform app. This results is a very inconvenient need to continuously switching between root project (in IntelliJ idea) and the Android (side-)project (in Android Studio).

Please allow "androidMain" folder to be another target platform SourceSet in the root project.

I tried to do this myself, but got an impression that this requires (or would be better done...) using Kotlin 1.4 multiplatform plugin, which supports more target SourceSets...

**Comment by yvolk** [comment]
Thank you @soywiz 
I upgraded korge-gradle-plugin to v.2.0.0.0-rc8
and I could almost completely reuse files used by Android build of the root project and of my customized Android project.

Now I can actually develop and run on Android emulator debug Android builds without switching to my customized Android project.
There are several bugs yet in the com.soywiz.korge.gradle.targets.android.AndroidDirectKt#configureAndroidDirect but they are not that critical for now...

**Comment by soywiz** [comment]
Glad to know now you can progress. Which other android-related bugs are you facing?

**Comment by yvolk** [comment]
I would love the bug with onClick event to be fixed first: https://github.com/korlibs/korge/issues/772 ...
Regarding AndroidDirect, as I remember:

1. No way to change "res" sources folder location, so I have to duplicate the same file(s) inside "main" and "commonMain" folders.
See how I point customized Android project to the shared folder (reused for all targets:
https://github.com/andstatus/game2048/blob/3a160f699b9294ea8319fa5e55daae76bb28fa8a/game2048-android/build.gradle#L74
````
    sourceSets {
        main {
            manifest.srcFile '../src/main/AndroidManifest.xml'
            java.srcDirs += [
                    "../src/main/java",
                    "../src/commonMain/kotlin",
                    "../src/androidMain/kotlin"]
            assets.srcDirs += [
                    "../src/commonMain/resources",
                    "../build/korgeProcessedResources/metadata/main"]
            res.srcDirs  += [
                    "../src/commonMain/resources/res"]
        }
    }
````

2. These properties aren't taken into account and default are used:
    androidMinSdk = 24
    androidCompileSdk = 29
    androidTargetSdk = 29
https://github.com/andstatus/game2048/blob/3a160f699b9294ea8319fa5e55daae76bb28fa8a/build.gradle.kts#L31

3. Even when overwrite.android.files=false and AndroidManifest.xml file is already present, the plugin creates app_icon.png, icon.png inside main/res/... 
Actually I would prefer in a case overwrite.android.files=false don't generate ANY Android project files (including also "korge.keystore")

4. versionName is always "1.0"
No way to set versionCode

5. Ideally the configureAndroidDirect should configure android plugin NOT in code, inserting lines in different sections (that is inflexible) but configure it using existing root or separate build.gradle(.kts) file. Like in normal Android build.gradle, where you have "android { }" section, can normally add dependencies, etc. …
That way a Developer will be able to fine-tune everything, including above-mentioned "bugs"/not implemented things.

**Comment by yvolk** [comment]
@soywiz Regarding a role of Korge plugin in configuring Android project during configureAndroidDirect I would say that the plugin should probably only update a list of Korge-related dependencies in a separate file to be included into the main Android build.gradle file (in an Android subproject). 
And not visa versa as it is now (I.e. now it is supposed that Korge plugin configures the whole Android build.gradle, and an app Developer includes into it something in his/her "build.extra...")

BTW, Kotlin MPP docs at https://kotlinlang.org/docs/reference/mpp-supported-platforms.html tell the same: "Manually apply an Android Gradle plugin – com.android.application..."

**Comment by soywiz** [comment]
Hey @yvolk sorry for the delay and thanks for your patience.

Can you create tasks for the things in the comment, or ping me on the issues that are opened already.
The idea is to move those tasks to the 2.0.x column here so we can prioritize them: https://github.com/orgs/korlibs/projects/1#column-11794735

**Comment by yvolk** [comment]
@soywiz Actually all numbered problems from my comment (and many more similar...) could be solved by changing a way the "targetAndroidDirect()" works. So I suggest to create **one** task on this, if you like this approach:

Regarding a role of Korge plugin in configuring Android project during configureAndroidDirect I would say that the plugin should probably only update a list of Korge-related dependencies in a separate file to be included into the main Android build.gradle file (in an Android subproject).
And not visa versa as it is now (I.e. now it is supposed that Korge plugin configures the whole Android build.gradle, and an app Developer includes into it something in his/her "build.extra...")

BTW, Kotlin MPP docs at https://kotlinlang.org/docs/reference/mpp-supported-platforms.html tell the same: "Manually apply an Android Gradle plugin – com.android.application..."

**Comment by yvolk** [comment]
@soywiz  Actually I tried to configure my https://github.com/andstatus/game2048/tree/master/game2048-android as a subproject of the multiplatform root project.
Android subproject works normally, but I lose all other targets (jsMain and mingwX64Main aren't source sets anymore...) so I reverted to the game2048-android invisible to the root project...
