### ISSUE TITLE
text2 works incorrectly with colon and semicolon symbols

### ISSUE THREAD

**Issue by Suragul** [korlibs/korge-next#79]
text2 works incorrectly with colon and semicolon symbols
Here is link: https://github.com/Suragul/text2Bug/tree/main/text2Bug

**Comment by soywiz** [comment]
The colon and semicolon issues were fixed here: https://github.com/korlibs/korge-next/issues/60
and will be available on `2.0.0-rc3`.

But I have noticed that the `\n` is not working properly now, so I'm going to keep the issue open.
