### ISSUE TITLE
Crash on K/N macosX64 macbook pro with touchbar when moving the mouse

### ISSUE THREAD

**Issue by soywiz** [korlibs/korge-next#80]
https://youtrack.jetbrains.com/issue/KT-43429

@dhakehurst

**Comment by soywiz** [comment]
@dhakehurst Can you download korge-next and try:

```
gradlew :samples:hello-world:runDebugExecutableMacosX64
```

And see if the crash persists?

**Comment by dhakehurst** [comment]
it does, but crashes even before I move the mouse now. In fact nothing starts up. See email for core-dump

**Comment by soywiz** [comment]
I will try to test on a macbook pro with touchbar asap. If I cannot have access to it this weekend or can't figure out the issue, I will defer this to a patch version (2.0.1 or so).

**Comment by soywiz** [comment]
No luck last weekend to get access to a macbook with touchbar, so this is deferred

**Comment by soywiz** [comment]
I have managed to reproduce it on an iMac by opening XCode and "Window" -> "Touch Bar" -> "Show Touch Bar"

**Comment by soywiz** [comment]
Update: I have provided a single-file reproducer at youtrack

**Comment by soywiz** [comment]
Update: There was a related issue already opened: https://youtrack.jetbrains.com/issue/KT-42482 once fixed, that should fix our issue too. In the meantime we cannot use the K/N macosX64 target on macbooks with touchbar. But we can still use the JVM target without issues in the meantime.

**Comment by soywiz** [comment]
Published korge `2.0.5.0` using Kotlin 1.3.40-RC that should fix this
