### ISSUE TITLE
Check sound JS issue

### ISSUE THREAD

**Issue by soywiz** [korlibs/korge-next#92]
From discord:
https://discord.com/channels/728582275884908604/728616340239417375/783638686817452032

**Comment by soywiz** [comment]
[jsissue.zip](https://github.com/korlibs/korge-next/files/5632364/jsissue.zip)

**Comment by soywiz** [comment]
Should be fixed on korge-next already (or can't reproduce it with the zip provided)

**Comment by lizpostudio** [comment]
Thank you! It works now!!!
